service: telegram-bot

custom:
  stage: test

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.6
  region: eu-west-1
  stackName: ${self:service}-cfn-lambda
  deploymentBucket:
    serverSideEncryption: AES256
  deploymentPrefix: serverless
  versionFunctions: false
  endpointType: regional

functions:
  telegaBot:
    package:
      include: ['lambda.py']
    handler: lambda.handler
    name: ${self:custom.stage}-${self:service}
    memorySize: 128
    timeout: 10
    environment:
      TOKEN: ${ssm:/aws/bot/telegram/token}

package:
  individually: true
  include: lambda.py
  exclude: [ "./node_modules/**","./.serverless/**" ]
